id: P4EA3DA72
initial_creation_type: ocr
source_metadata:
  volumes:
    72ff5a2c0c914e5391ffeb5eb5af6f3b:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: སློབ་དཔོན་པདྨ་དགེ་བསྙེན་གྱིས་འཇིག་རྟེན་དབང་ཕྱུག་ལས་གྲུབ་པ་ཐོབ་པའི་ལོ་རྒྱུས།
      total_pages: 1872
      volume_number: 114
